### ISSUE TITLE
Error when joining nodes to the cluster

### ISSUE THREAD

**Issue by inful** [luxas/kubeadm-workshop#1]
When following the instructions, I get the following when trying to join a node to the cluster:

```
discovery] Failed to connect to API Server "192.168.0.8:6443": there is no JWS signed token in the cluster-info ConfigMap. This token id "753691" is invalid for this cluster, can't connect
```

**Comment by inful** [comment]
Sorry, this was due to some other issue.

**Comment by luxas** [comment]
No no, this was a real issue, I'm very glad you reported it.
However, I've been (or am) traveling now for quite some time and have had internet access occasionally, so didn't get to answering your issue before now.

However, there's absolutely no need to be sorry, this error was due to that kubeadm explicitely enables two disabled-by-default controllers, but when I specified `controllers` in the config file, I forgot to add those and therefore one couldn't use the token join flow. This was corrected yesterday or so, and should now be working

I hope you enjoy this workshop, thanks for testing it out so quickly :+1: 

And when you find an other bug, don't hesitate to create an issue again :smile:
