### ISSUE TITLE
Setup does not survive a reboot

### ISSUE THREAD

**Issue by inful** [luxas/kubeadm-workshop#3]
I don't know if that is as intended, but after a reboot the master node is unable to bring up the cluster again.

**Comment by luxas** [comment]
That's a known issue, and is due to how self-hosting is implemented in kubeadm for the moment (it's alpha :smile:). Basically, there is no checkpointer atm, so when kubelet comes up the 2nd time it don't know what to run (tries to get information from the API, which waits for kubelet to start it).

Right now self-hosting is required for this guide, but it won't be in the future.

Would you like to contribute a "known issues" section and add this? :smile:

**Comment by luxas** [comment]
Perfect, fixed with #4

**Comment by luxas** [comment]
I've now stopped using the self-hosted mode, so I expect reboots to start working again.
Will create an issue to remove that known limitation if I'm successful restarting a node/master
